INSERT INTO consultation (
    consultation_date,
    reason,
    treatment,
    note,
    medical_exam,
    exclusion_test,
    given_advice,
    given_exercise,
    food_supplement,
    patient_id,
    practitioner_id
) VALUES

      ('2026-01-05 09:00:00',
       'Douleurs lombaires après déménagement',
       'Mobilisations lombaires et travail myofascial',
       'Bonne réponse au traitement',
       'Limitation flexion lombaire',
       'Aucun signe neurologique',
       'Hydratation et éviter le port de charges lourdes',
       'Étirements lombaires quotidiens',
       'Magnésium',
       12,
       1),

      ('2026-01-12 14:30:00',
       'Cervicalgies liées au travail sur écran',
       'Technique fonctionnelle cervicale',
       'Tensions importantes trapèzes',
       'Restriction rotation cervicale droite',
       'Test de compression négatif',
       'Ajuster la posture au bureau',
       'Auto-grandissement cervical',
       NULL,
       11,
       1),

      ('2026-01-18 11:00:00',
       'Maux de tête récurrents',
       'Travail cranio-sacré et cervical',
       'Amélioration immédiate',
       'Hypertonie sous-occipitale',
       'Pas de drapeau rouge',
       'Réduire le stress',
       'Respiration diaphragmatique',
       NULL,
       4,
       1),

      ('2026-02-02 10:00:00',
       'Douleur épaule droite',
       'Mobilisation gléno-humérale',
       'Amplitude améliorée',
       'Restriction abduction',
       'Test de conflit léger',
       'Éviter les mouvements répétitifs',
       'Renforcement coiffe des rotateurs',
       'Oméga 3',
       12,
       1),

      ('2026-02-15 16:00:00',
       'Sciatique légère',
       'Décompression lombaire douce',
       'Douleur diminuée',
       'Tension chaîne postérieure',
       'Lasègue négatif',
       'Marche quotidienne',
       'Étirement ischio-jambiers',
       'Magnésium',
       7,
       1),

      ('2026-03-01 09:30:00',
       'Suivi lombalgie',
       'Rééquilibrage bassin',
       'Amélioration continue',
       'Mobilité satisfaisante',
       'RAS',
       'Poursuite des exercices',
       'Gainage abdominal',
       NULL,
       12,
       1),

      ('2026-03-12 15:15:00',
       'Douleurs thoraciques mécaniques',
       'Mobilisation costale',
       'Soulagement immédiat',
       'Restriction mobilité costale',
       'Exclusion pathologie cardiaque',
       'Travail respiratoire',
       'Exercices d’ouverture thoracique',
       NULL,
       7,
       1),

      ('2026-04-03 08:45:00',
       'Tensions mandibulaires',
       'Travail ATM et muscles masticateurs',
       'Bruxisme nocturne confirmé',
       'Hypertonie masséters',
       'RAS',
       'Consulter dentiste pour gouttière',
       'Relaxation mâchoire',
       'Magnésium',
       10,
       1),

      ('2026-04-20 13:00:00',
       'Douleurs genou gauche',
       'Travail articulaire et fascial',
       'Amélioration modérée',
       'Restriction rotation tibiale',
       'Tests ligamentaires négatifs',
       'Reprise progressive du sport',
       'Renforcement quadriceps',
       'Collagène',
       10,
       1),

      ('2026-05-08 17:00:00',
       'Bilan de contrôle',
       'Traitement global préventif',
       'Aucune plainte particulière',
       'Examen satisfaisant',
       'RAS',
       'Maintenir activité physique régulière',
       'Mobilité générale',
       NULL,
       12,
       1);
